
version: 2

models:
    - name: locked_attributes
      description: "When an auction was locked"
      columns:
          - name: auction_id
            description: "auction id"
            tests:
                - unique
                - not_null
          - name: price_when_locked
          - name: retrieval_time_when_locked
    - name: aggregated_attributes
      description: "Auction attributes from the bid history grouped by auction id"
      columns:
          - name: auction_id
            description: "auction id"
            tests:
                - unique
                - not_null
          - name: min_retrieval_time
          - name: max_retrieval_time
          - name: duration_seconds
          - name: count_distinct_bidders
          - name: count_total_bids
          - name: count_winner_bids
          - name: count_single_bid
          - name: count_bidomatic